# Generated by Django 3.0.2 on 2020-01-29 08:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Movie', '0004_product_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_info',
            name='product',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Movie.Product'),
        ),
        migrations.AddField(
            model_name='product_info',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
