# Generated by Django 3.0.2 on 2020-01-30 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movie', '0006_delete_booking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product_info',
            name='img6',
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.FileField(upload_to=''),
        ),
    ]
