# Generated by Django 3.0.2 on 2020-01-31 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movie', '0007_auto_20200130_1803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_info',
            name='img1',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='product_info',
            name='img2',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='product_info',
            name='img3',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='product_info',
            name='img4',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='product_info',
            name='img5',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='product_info',
            name='title_img',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
