# Generated by Django 3.0.2 on 2020-01-31 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Movie', '0008_auto_20200131_1458'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product_info',
            name='user',
        ),
    ]
