# Generated by Django 3.0.2 on 2020-01-31 09:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Movie', '0009_remove_product_info_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product_info',
            name='img5',
        ),
        migrations.AddField(
            model_name='product_info',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
