# Generated by Django 3.0.2 on 2020-02-01 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movie', '0014_moviebook'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_info',
            name='img5',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
