# Generated by Django 3.0.2 on 2020-02-02 03:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Movie', '0014_moviebook'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product_info',
            new_name='Single_Movie',
        ),
    ]
