# Generated by Django 3.0.2 on 2020-02-02 03:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Movie', '0015_auto_20200202_0938'),
    ]

    operations = [
        migrations.CreateModel(
            name='Single_Movies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('title_img', models.FileField(blank=True, upload_to='')),
                ('img1', models.FileField(blank=True, upload_to='')),
                ('img2', models.FileField(blank=True, upload_to='')),
                ('img3', models.FileField(blank=True, upload_to='')),
                ('img4', models.FileField(blank=True, upload_to='')),
                ('product', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Movie.Product')),
            ],
        ),
        migrations.DeleteModel(
            name='Single_Movie',
        ),
    ]
