# Generated by Django 3.0.2 on 2020-02-02 04:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Movie', '0016_auto_20200202_0939'),
        ('Movie', '0016_remove_product_info_img5'),
    ]

    operations = [
    ]
