# Generated by Django 3.0.2 on 2020-02-02 04:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Movie', '0017_merge_20200202_0945'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Single_Movies',
            new_name='Product_info',
        ),
    ]
