# Generated by Django 3.0.2 on 2020-02-02 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movie', '0018_auto_20200202_0946'),
    ]

    operations = [
        migrations.AddField(
            model_name='moviebook',
            name='Booked_date',
            field=models.DateField(default=''),
        ),
        migrations.AddField(
            model_name='moviebook',
            name='Expiry_date',
            field=models.DateField(default=''),
        ),
        migrations.AddField(
            model_name='moviebook',
            name='Time',
            field=models.TimeField(default=''),
        ),
    ]
