# Generated by Django 3.0.2 on 2020-02-03 05:59

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Movie', '0024_auto_20200203_1142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviebook',
            name='Booked_date',
            field=models.DateField(default=datetime.datetime(2020, 2, 3, 5, 59, 12, 784330, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='moviebook',
            name='Expiry_date',
            field=models.DateField(default=datetime.datetime(2020, 2, 3, 5, 59, 12, 784330, tzinfo=utc)),
        ),
    ]
