# Generated by Django 3.0.2 on 2020-02-04 06:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Movie', '0028_auto_20200204_1200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviebook',
            name='Expiry_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
