# Generated by Django 3.0.2 on 2020-02-04 13:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Movie', '0034_auto_20200204_1920'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moviebook',
            name='Booked_date',
        ),
        migrations.RemoveField(
            model_name='moviebook',
            name='Expiry_date',
        ),
        migrations.CreateModel(
            name='Ticketbooking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=10)),
                ('quantity', models.IntegerField()),
                ('price', models.IntegerField()),
                ('Time', models.CharField(max_length=50)),
                ('Booked_date', models.DateField(blank=True, default='<jamming-date>')),
                ('Expiry_date', models.DateField(blank=True, default='<jamming-date>')),
                ('movie_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Movie.Product')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
