# Generated by Django 3.0.2 on 2020-02-04 13:46

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Movie', '0036_auto_20200204_1928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketbooking',
            name='Booked_date',
            field=models.DateField(verbose_name=datetime.datetime(2020, 2, 4, 13, 46, 28, 502438, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='ticketbooking',
            name='Expiry_date',
            field=models.DateField(verbose_name=datetime.datetime(2020, 2, 4, 13, 46, 28, 502438, tzinfo=utc)),
        ),
    ]
