# Generated by Django 3.0.2 on 2020-02-04 13:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movie', '0037_auto_20200204_1931'),
    ]

    operations = [
        migrations.AddField(
            model_name='moviebook',
            name='Booked_date',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 1, 9, 0, 0)),
        ),
        migrations.AddField(
            model_name='moviebook',
            name='Expiry_date',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 1, 9, 0, 0)),
        ),
        migrations.DeleteModel(
            name='Ticketbooking',
        ),
    ]
