# Generated by Django 3.0.2 on 2020-02-04 13:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movie', '0040_auto_20200204_1936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviebook',
            name='Booked_date',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 2, 4, 0, 0)),
        ),
        migrations.AlterField(
            model_name='moviebook',
            name='Expiry_date',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 2, 4, 0, 0)),
        ),
    ]
