# Generated by Django 3.0.2 on 2020-02-04 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movie', '0041_auto_20200204_1937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviebook',
            name='Booked_date',
            field=models.DateField(blank=True, default='datetime(2020,2,4)'),
        ),
        migrations.AlterField(
            model_name='moviebook',
            name='Expiry_date',
            field=models.DateField(blank=True, default='datetime(2020,2,4)'),
        ),
    ]
