# Generated by Django 3.0.2 on 2020-02-04 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movie', '0042_auto_20200204_1938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviebook',
            name='Booked_date',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='moviebook',
            name='Expiry_date',
            field=models.DateField(blank=True),
        ),
    ]
