# Generated by Django 3.0.2 on 2020-02-04 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movie', '0045_auto_20200204_1951'),
    ]

    operations = [
        migrations.AddField(
            model_name='moviebook',
            name='Booked_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='moviebook',
            name='Expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
