# Generated by Django 3.0.2 on 2020-02-04 14:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Movie', '0047_auto_20200204_1953'),
    ]

    operations = [
        migrations.AddField(
            model_name='moviebook',
            name='Booked_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='moviebook',
            name='Expiry_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
