# Generated by Django 3.0.2 on 2020-02-04 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Movie', '0048_auto_20200204_1954'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MovieBook',
        ),
    ]
