# Generated by Django 3.0.2 on 2020-02-05 08:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Movie', '0050_moviebook'),
    ]

    operations = [
        migrations.AddField(
            model_name='moviebook',
            name='time',
            field=models.CharField(default=django.utils.timezone.now, max_length=30),
            preserve_default=False,
        ),
    ]
