# Generated by Django 3.0.2 on 2020-02-05 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movie', '0052_auto_20200205_1421'),
    ]

    operations = [
        migrations.RenameField(
            model_name='moviebook',
            old_name='Booked_date',
            new_name='BookedDate',
        ),
        migrations.RenameField(
            model_name='moviebook',
            old_name='Expiry_date',
            new_name='ExpiryDate',
        ),
        migrations.AlterField(
            model_name='moviebook',
            name='time',
            field=models.CharField(default='', max_length=30),
        ),
    ]
