# Generated by Django 3.0.2 on 2020-02-05 08:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Movie', '0053_auto_20200205_1422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviebook',
            name='BookedDate',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='moviebook',
            name='ExpiryDate',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
