# Generated by Django 3.0.2 on 2020-02-05 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movie', '0054_auto_20200205_1426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviebook',
            name='BookedDate',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='moviebook',
            name='ExpiryDate',
            field=models.DateField(default='', max_length=100),
        ),
    ]
