# Generated by Django 3.0.2 on 2020-02-05 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movie', '0055_auto_20200205_1432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviebook',
            name='ExpiryDate',
            field=models.CharField(default='', max_length=100),
        ),
    ]
