# Generated by Django 3.0.2 on 2020-02-05 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movie', '0056_auto_20200205_1436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviebook',
            name='BookedDate',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='moviebook',
            name='ExpiryDate',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='moviebook',
            name='time',
            field=models.CharField(default='', max_length=40),
        ),
    ]
