# Generated by Django 3.0.2 on 2020-02-07 08:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Movie', '0057_auto_20200205_2057'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_info',
            name='AvailableSeats',
            field=models.IntegerField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
